- .eslintrc
- package-lock.json
- package.json
> add airbnb linter and eslint rules

- src/components/foundation/grid/GRID.md
- src/components/foundation/icons/ICONS.md
- src/components/foundation/typography/TYPOGRAPHY.md
- styleguide.config.js
Bonjour,
Merci pour ce repo;
Je vous propose quelques corrections de typo et l'utilisation de la couleur "Bleu France" pour le theme styleguidist
> chore: small fixes

- src/components/interface/Breadcrumb/Breadcrumb.js
- src/components/interface/Breadcrumb/BreadcrumbItem.js
- src/components/interface/Card/Card.js
- src/components/interface/Card/CardDescription.js
- src/components/interface/Card/CardDetail.js
- src/components/interface/Card/CardImage.js
- src/components/interface/Card/CardTitle.js
- src/components/interface/Footer/Footer.js
- src/components/interface/Footer/FooterBody.js
- src/components/interface/Footer/FooterBottom.js
- src/components/interface/Footer/FooterCopy.js
- src/components/interface/Footer/FooterLink.js
- src/components/interface/Footer/FooterPartners.js
- src/components/interface/Footer/FooterPartnersLogo.js
- src/components/interface/Footer/FooterPartnersTitle.js
- src/components/interface/Footer/FooterTop.js
- src/components/interface/Footer/FooterTopCategory.js
- src/components/interface/Header/Header.js
- src/components/interface/Header/HeaderBody.js
- src/components/interface/Header/HeaderNav.js
- src/components/interface/Header/Service.js
- src/components/interface/Header/Tool.js
- src/components/interface/Header/ToolItemGroup.js
- src/components/interface/Logo/Logo.js
- src/components/interface/Modal/Modal.js
- src/components/interface/Modal/ModalClose.js
- src/components/interface/Modal/ModalContent.js
- src/components/interface/Modal/ModalFooter.js
- src/components/interface/Modal/ModalTitle.js
- src/utils/type-validation.js
fix https://github.com/dataesr/react-dsfr/issues/102
> Use __TYPE instead of component name

- package-lock.json
- src/components/interface/Button/Button.js
- src/components/interface/Button/__tests__/ButtonGroup.test.js
- src/components/interface/Button/__tests__/__snapshots__/Button.test.js.snap
- src/components/interface/Button/__tests__/__snapshots__/ButtonGroup.test.js.snap
- src/components/interface/Button/index.js
- src/components/interface/Callout/__tests__/Callout.test.js
- src/components/interface/Callout/__tests__/__snapshots__/Callout.test.js.snap
- src/components/interface/Modal/Modal.js
- src/components/interface/Modal/__tests__/Modal.test.js
- src/components/interface/Modal/__tests__/__snapshots__/Modal.test.js.snap
- src/index.js
add buttongroup to exports, 
button no title required and prop styleAsLink, 
modal fix alignement and sizes
> [Fix] Buttons and modal

- example/src/App.js
- example/src/components/Media/Media.jsx
- example/src/components/Summary/Summary.jsx
- src/components/interface/Summary/Summary.js
- src/components/interface/Summary/Summary.md
- src/components/interface/Summary/SummaryItem.js
- src/components/interface/Summary/__tests__/Summary.test.js
- src/components/interface/Summary/__tests__/__snapshots__/Summary.test.js.snap
- src/components/interface/Summary/index.js
- src/components/interface/Summary/summary.css
- src/index.js
closes https://github.com/dataesr/react-dsfr/issues/93
> Add Summary component

- example/src/components/Header/Header.jsx
- src/components/interface/Header/Header.md
- src/components/interface/Header/HeaderBody.js
- src/components/interface/Header/HeaderOperator.js
- src/components/interface/Header/__tests__/Header.test.js
- src/components/interface/Header/__tests__/__snapshots__/Header.test.js.snap
- src/components/interface/Header/index.js
- src/index.js
> Add header operator

- example/src/components/Radio/Radio.jsx
- package-lock.json
- package.json
- src/components/interface/Radio/Radio.js
- src/components/interface/Radio/RadioGroup.js
- src/components/interface/Radio/__tests__/RadioGroup.test.js
- src/components/interface/Radio/__tests__/__snapshots__/Radio.test.js.snap
- src/components/interface/Radio/__tests__/__snapshots__/RadioGroup.test.js.snap
Managed a controlled mode directly on the radio group
Add checked attribute to the input dom
Fix issue when it was not possible to have two checkboxes on the same pages
> Improve radio button

- src/components/foundation/typography/Text/Text.js
- src/components/foundation/typography/Title/Title.js
- src/components/foundation/typography/TitleDisplay/TitleDisplay.js
- src/components/interface/Breadcrumb/BreadcrumbItem.js
- src/components/interface/Button/Button.js
- src/components/interface/Callout/CalloutText.js
- src/components/interface/Callout/CalloutTitle.js
- src/components/interface/Card/CardDescription.js
- src/components/interface/Card/CardDetail.js
- src/components/interface/Card/CardTitle.js
- src/components/interface/Footer/FooterCopy.js
- src/components/interface/Footer/FooterLink.js
- src/components/interface/Footer/FooterPartnersTitle.js
- src/components/interface/Header/ToolItem.js
- src/components/interface/Highlight/Highlight.js
- src/components/interface/Logo/Logo.js
- src/components/interface/Modal/ModalClose.js
- src/components/interface/Modal/ModalTitle.js
- src/components/interface/SideMenu/SideMenuLink.js
- src/components/interface/Skiplinks/SkiplinkItem.js
- src/components/interface/Tag/Tag.js
> Allow for string and node children

- src/components/interface/Header/NavItem.js
- src/components/interface/Header/NavSubItem.js
- src/components/interface/Header/ToolItem.js
- src/components/interface/Link/Link.js
When you are on mobile view and using React Router Links, the page is not reloaded so the burger menu does not close
> Close burger menu on mobil view when clicking an element

- example/src/App.js
- example/src/components/Alert/Alert.jsx
- src/components/interface/Alert/Alert.js
- src/components/interface/Alert/Alert.md
- src/components/interface/Alert/__tests__/Alert.test.js
- src/components/interface/Alert/__tests__/__snapshots__/Alert.test.js.snap
- src/components/interface/Alert/index.js
- src/index.js
https://gouvfr.atlassian.net/wiki/spaces/DB/pages/736362500/Alertes+-+Alerts
> Add Alert component

- src/components/interface/Button/ButtonGroup.js
- src/components/interface/Checkbox/Checkbox.js
- src/components/interface/Header/Header.js
- src/components/interface/Header/HeaderNav.js
- src/components/interface/Header/MegaNavItem.js
- src/components/interface/Header/MegaNavSubItem.js
- src/components/interface/Header/NavItemWithSubItems.js
- src/components/interface/Header/ToolItem.js
- src/components/interface/Header/__tests__/__snapshots__/Header.test.js.snap
- src/components/interface/Logo/Logo.js
- src/components/interface/Radio/Radio.js
- src/components/interface/SearchBar/SearchBar.js
- src/components/interface/Select/SearcheableSelect.js
- src/components/interface/Select/Select.js
- src/components/interface/Select/SelectWrapper.js
- src/components/interface/Select/__tests__/__snapshots__/Select.test.js.snap
- src/components/interface/SideMenu/SideMenu.js
- src/components/interface/SideMenu/SideMenuItem.js
- src/components/interface/SideMenu/__tests__/__snapshots__/SideMenu.test.js.snap
- src/components/interface/Tag/TagGroup.js
- src/components/interface/TextInput/TextInput.js
- src/components/interface/TextInput/__tests__/__snapshots__/TextInput.test.js.snap
- src/components/interface/Toggle/Toggle.js
put random ids inside a ref to avoid regenerating it at each render
use index as key for mapping... not ideal and I'm not sure that's even a good idea...
> Get ride of extra rendering because of uuid

- src/components/interface/Header/ToolItemGroup.js
Menu links where not showing when switching from desktop to mobile
> Fix burger menu in mobile

- src/components/interface/Footer/FooterLink.js
> fix(footer-link): Support "target" attribute

- .github/workflows/build.yml
- src/components/interface/Tabs/Tab.d.ts
- src/components/interface/Tabs/index.d.ts
Bonjour,
Suite à cette PR : https://github.com/dataesr/react-dsfr/pull/230/files, le projet ne pouvait pas build.
Du coup, sur cette PR, je corrige cela, et rajoute sur le github workflow, un test vérifiant que le projet build bien
> fix: missing types + build

- README.md
> docs(readme): add some users

- src/components/interface/TextInput/TextInput.d.ts
https://github.com/dataesr/react-dsfr/issues/242
> fix: add htmlinput element properties in TextInput

- README.md
Hello again,  
Just some little formating patches for the README.  
Best regards,
> chore: Update README formating

- src/components/interface/SwitchTheme/SwitchTheme.js
fix https://github.com/dataesr/react-dsfr/issues/290
> fix: SSR on switch theme

- src/components/interface/SwitchTheme/SwitchTheme.js
prevent SSR issue with SwicthTheme component
> fix(SwitchMode): fix SSR fix #290

- .github/workflows/tests.yml
- src/components/interface/Footer/__tests__/__snapshots__/Footer.test.js.snap
- src/components/interface/SwitchTheme/SwitchTheme.js
This allows to run tests if the pull request comes from a forked repository.
Fixes broken tests.
> ci: :construction_worker: Run CI tests on pull requests, not only git pushes
